### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mdpiper** [equib/proEQUIB#3]
See description in https://github.com/atomneb/AtomNeb-idl/issues/2.

**Comment by danehkar** [comment]
> See description in [atomneb/AtomNeb-idl#2](https://github.com/atomneb/AtomNeb-idl/issues/2).

@mdpiper @mgalloy I added  [mgunit](https://github.com/mgalloy/mgunit) in the folder  [test_mgunit](https://github.com/equib/proEQUIB/tree/master/test_mgunit) for automated tests. You need to have atomic data in ``externals/atomneb/atomic-data`` and ``externals/atomneb/atomic-data-rc`` in order to use it. To have all dependencies, you can clone the whole project with dependent libraries:

    git clone --recursive https://github.com/equib/proEQUIB.git

Then, you can run the test for mgunit:

    idl test_all.pro

There should not be any failure in ``test-results.log`` and ``test-results.html`` files.

I also noticed that `triangulate` and `trigrid` of GDL does not work properly in [interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro). I replaced [interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro) with [interp_2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp_2d.pro). Now API functions also work in GDL. To check, you need to install [GDL](https://github.com/gnudatalanguage/gdl) on your machine. As you see in [Travis CI](https://travis-ci.org/equib/proEQUIB) and [Appveyor](https://ci.appveyor.com/project/danehkar/proequib), the API functions work without any problems in GDL.

**Comment by mgalloy** [comment]
All tests are passing on my system as well.

**Comment by danehkar** [comment]
> All tests are passing on my system as well.

Thank you for the test.
